### ISSUE TITLE
Update/Upgrade to Freedesktop 18.08

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.freedesktop.Sdk.Extension.gfortran-62#3]
flathub/org.freedesktop.Sdk.Extension.gcc8#3
flathub/org.freedesktop.Sdk.Extension.openjdk10#5

Thanks!

**Comment by barthalion** [comment]
@jjardon @bochecha Is it provided by 18.08?

**Comment by bochecha** [comment]
Yes, gfortran is in the 18.08 sdk.

We discovered that after the release, though, so we probably won't move it to an extension.

We should probably make it an extension for 19.08 though.

**Comment by barthalion** [comment]
I'm fine with it being part of the new runtime honestly, we just need to communicate the change/update apps ourselves.

**Comment by nedrichards** [comment]
Yeah, it's more of a size vs usefulness for every app question I suspect.
